name: 😼 Test Build

on:
  push:
    branches:
      - main
      - build
  pull_request:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 'latest'

    - name: Build
      run: |
        $sha = (git rev-parse --short HEAD)
        echo 'node-linker=hoisted' > .npmrc # make it work with electron
        pnpm i --frozen-lockfile
        $env:SHORT_SHA=$sha; pnpm run build:ci

    - name: Move artifacts
      id: vars
      shell: pwsh
      run: |
        $sha = (git rev-parse --short HEAD)
        md -Name ./dist/artifacts -Force
        Compress-Archive -Path ./dist/win-unpacked -DestinationPath ./dist/artifacts/win-unpacked-x64.zip
        Copy-Item ./dist/*.exe -Destination ./dist/artifacts/
        $file = Get-ChildItem -Path ./dist/artifacts/ -Filter "*.exe" | select-object -first 1
        $newName = "$($file.BaseName).$($sha)$($file.Extension)"
        Rename-Item -Path $file.FullName -NewName $newName
        echo "::set-output name=fileName::$($newName)"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          dist/artifacts/*.zip
          dist/artifacts/*.exe
        # name: ${{ steps.vars.outputs.fileName }}
